# Site settings
title: 包給力 Givespower.health
email: givespower.health@gmail.com

# Development Settings
baseurl: "/"
url: "http://localhost:4000"

include: ["_pages"]
logo: 'img/logo/logo.png'

line_url: https://lin.ee/Umt7lpD
instagram_url: https://www.instagram.com/givespower.health
address_url: https://maps.app.goo.gl/V34db2nEdmVg2K6t7

# Developer settings
developer_name: Crystal Chang

